package com.mshdabiola.database

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.mshdabiola.database.dao.NoteDao
import com.mshdabiola.database.dao.NoteImageDao
import com.mshdabiola.database.model.NoteEntity
import com.mshdabiola.database.model.NoteImageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.io.IOException
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class NoteImageDaoTest {

    private lateinit var database: NotesDatabase
    private lateinit var noteImageDao: NoteImageDao
    private lateinit var noteDao: NoteDao

    private var testNoteId1: Long = -1L
    private var testNoteId2: Long = -1L

    // Since NoteImageEntity.id is not auto-generated, we'll manage some test IDs
    private val testImageId1: Long = 1001L
    private val testImageId2: Long = 1002L
    private val testImageId3: Long = 1003L
    private val testImageId4: Long = 1004L


    @Before
    fun createDb() = runTest {
        database = Room.inMemoryDatabaseBuilder<NotesDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()
        noteImageDao = database.getNoteImageDao()
        noteDao = database.getNoteDao()

        testNoteId1 = noteDao.upsert(NoteEntity(
            id = null,
            title = "Image Note 1",
            detail = "",
            editDate = 0L,
            isCheck = false,
            color = 0,
            background = 0,
            isPin = false,
            noteType = 0,
        ))
        testNoteId2 = noteDao.upsert(NoteEntity(
            id = null,
            title = "Image Note 2",
            detail = "",
            editDate = 0L,
            isCheck = false,
            color = 0,
            background = 0,
            isPin = false,
            noteType = 0,
        ))
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        database.close()
    }

    @Test
    fun upsertAndGetImage() = runTest {
        val image = NoteImageEntity(id = testImageId1, noteId = testNoteId1)
        noteImageDao.upsert(image) // Returns rowId, not the provided id

        val retrievedImage = noteImageDao.get(testImageId1).first()
        assertNotNull(retrievedImage)
        assertEquals(testImageId1, retrievedImage.id)
        assertEquals(testNoteId1, retrievedImage.noteId)
    }

    @Test
    fun upsert_updatesExistingImage() = runTest {
        // Note: For entities with non-autogenerated PKs, "update" means replacing the row.
        // If we want to change the noteId for an image, it's effectively a new association.
        // Let's test inserting then "replacing" it (which Room handles as an update if PK matches)
        val initialImage = NoteImageEntity(id = testImageId1, noteId = testNoteId1)
        noteImageDao.upsert(initialImage)

        // For NoteImageEntity, an "update" would usually involve changing other fields if it had them.
        // Since it only has id and noteId, and id is PK, only noteId can realistically be "updated".
        // Let's assume we are re-associating this image ID with a new note ID.
        val updatedImage = NoteImageEntity(id = testImageId1, noteId = testNoteId2)
        noteImageDao.upsert(updatedImage)

        val retrieved = noteImageDao.get(testImageId1).first()
        assertNotNull(retrieved)
        assertEquals(testImageId1, retrieved.id)
        assertEquals(testNoteId2, retrieved.noteId, "Note ID should be updated")
    }


    @Test
    fun upserts_insertsMultipleImages() = runTest {
        val images = listOf(
            NoteImageEntity(id = testImageId1, noteId = testNoteId1),
            NoteImageEntity(id = testImageId2, noteId = testNoteId1)
        )
        val rowIds = noteImageDao.upserts(images)
        assertEquals(2, rowIds.size)
        assertTrue(rowIds.all { it > 0 }) // Check if SQLite row IDs are valid

        val retrievedImages = noteImageDao.getByNoteId(testNoteId1).first()
        assertEquals(2, retrievedImages.size)
        assertTrue(retrievedImages.any { it.id == testImageId1 })
        assertTrue(retrievedImages.any { it.id == testImageId2 })
    }

    @Test
    fun getByNoteId_returnsCorrectImages() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId2))
        noteImageDao.upsert(NoteImageEntity(id = testImageId3, noteId = testNoteId1))

        val imagesForNote1 = noteImageDao.getByNoteId(testNoteId1).first()
        assertEquals(2, imagesForNote1.size)
        assertTrue(imagesForNote1.all { it.noteId == testNoteId1 })

        val imagesForNote2 = noteImageDao.getByNoteId(testNoteId2).first()
        assertEquals(1, imagesForNote2.size)
        assertEquals(testNoteId2, imagesForNote2.first().noteId)
        assertEquals(testImageId2, imagesForNote2.first().id)
    }

    @Test
    fun getImage_nonExistent() = runTest {
        val image = noteImageDao.get(9999L).first() // ID that doesn't exist
        assertNull(image)
    }

    @Test
    fun getAll_whenEmpty() = runTest {
        noteImageDao.deleteByNoteId(testNoteId1)
        noteImageDao.deleteByNoteId(testNoteId2)
        val allImages = noteImageDao.getAll().first()
        assertTrue(allImages.isEmpty())
    }

    @Test
    fun getAll_afterInserts() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId2))
        val allImages = noteImageDao.getAll().first()
        assertEquals(2, allImages.size)
    }

    @Test
    fun deleteImage() = runTest {
        val image = NoteImageEntity(id = testImageId1, noteId = testNoteId1)
        noteImageDao.upsert(image)
        assertNotNull(noteImageDao.get(testImageId1).first())

        noteImageDao.delete(testImageId1) // Delete by NoteImageEntity.id
        assertNull(noteImageDao.get(testImageId1).first())
    }

    @Test
    fun deleteByNoteId_deletesAllImagesForNote() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId1))
        noteImageDao.upsert(NoteImageEntity(id = testImageId3, noteId = testNoteId2))

        noteImageDao.deleteByNoteId(testNoteId1)

        assertTrue(noteImageDao.getByNoteId(testNoteId1).first().isEmpty())
        assertEquals(1, noteImageDao.getByNoteId(testNoteId2).first().size, "Should not delete images from other notes")
        assertEquals(testImageId3, noteImageDao.getByNoteId(testNoteId2).first().firstOrNull()?.id)
    }
}
