/*
 * Designed and developed by 2024 mshdabiola (lawal abiola)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mshdabiola.database

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.mshdabiola.database.dao.NoteDao
import com.mshdabiola.database.dao.NoteImageDao
import com.mshdabiola.database.model.NoteEntity
import com.mshdabiola.database.model.NoteImageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.io.IOException
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class NoteImageDaoTest {

    private lateinit var database: NotesDatabase
    private lateinit var noteImageDao: NoteImageDao
    private lateinit var noteDao: NoteDao

    private var testNoteId1: Long = -1L
    private var testNoteId2: Long = -1L

    private val testImageId1: Long = 1001L
    private val testImageId2: Long = 1002L
    private val testImageId3: Long = 1003L

    private fun createTestNoteEntity(title: String): NoteEntity = NoteEntity(
        id = null, // Auto-generated by Room
        title = title,
        detail = "Test Detail for $title",
        editDate = System.currentTimeMillis(),
        isCheck = false,
        color = 0,
        background = 0,
        isPin = false,
        noteType = 0,
    )

    @Before
    fun createDb() = runTest {
        database = Room.inMemoryDatabaseBuilder<NotesDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO) // Use IO dispatcher for test queries
            .build()
        noteImageDao = database.getNoteImageDao()
        noteDao = database.getNoteDao()

        // Insert parent NoteEntities to satisfy foreign key constraints
        testNoteId1 = noteDao.upsert(createTestNoteEntity("Image Note 1"))
        testNoteId2 = noteDao.upsert(createTestNoteEntity("Image Note 2"))
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        database.close()
    }

    @Test
    fun upsertAndGetImage() = runTest {
        val path = "path/to/image1.jpg"
        val image = NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = path)
        val returnedId = noteImageDao.upsert(image)
        assertEquals(testImageId1, returnedId) // For non-autoGen PK, upsert returns the ID

        val retrievedImage = noteImageDao.get(testImageId1).first()
        assertNotNull(retrievedImage)
        assertEquals(testImageId1, retrievedImage.id)
        assertEquals(testNoteId1, retrievedImage.noteId)
        assertEquals(path, retrievedImage.path)
    }

    @Test
    fun upsert_updatesExistingImage() = runTest {
        val initialPath = "path/initial.jpg"
        val updatedPath = "path/updated.jpg"

        val initialImage = NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = initialPath)
        noteImageDao.upsert(initialImage)

        val updatedImage = NoteImageEntity(id = testImageId1, noteId = testNoteId2, path = updatedPath)
        noteImageDao.upsert(updatedImage)

        val retrieved = noteImageDao.get(testImageId1).first()
        assertNotNull(retrieved)
        assertEquals(testImageId1, retrieved.id)
        assertEquals(testNoteId2, retrieved.noteId, "Note ID should be updated")
        assertEquals(updatedPath, retrieved.path, "Path should be updated")
    }

    @Test
    fun upserts_insertsMultipleImages() = runTest {
        val images = listOf(
            NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "path1.jpg"),
            NoteImageEntity(id = testImageId2, noteId = testNoteId1, path = "path2.jpg"),
        )
        val returnedIds = noteImageDao.upserts(images)
        assertEquals(2, returnedIds.size)
        assertTrue(
            returnedIds.containsAll(listOf(testImageId1, testImageId2)),
            "Returned IDs should match input IDs",
        )

        val retrievedImages = noteImageDao.getByNoteId(testNoteId1).first()
        assertEquals(2, retrievedImages.size)
        assertTrue(retrievedImages.any { it.id == testImageId1 && it.path == "path1.jpg" })
        assertTrue(retrievedImages.any { it.id == testImageId2 && it.path == "path2.jpg" })
    }

    @Test
    fun upserts_updatesAndInsertsImages() = runTest {
        val image1Initial = NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "initial1.jpg")
        noteImageDao.upsert(image1Initial) // Pre-insert one image

        val image1Updated = NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "updated1.jpg")
        val image2New = NoteImageEntity(id = testImageId2, noteId = testNoteId1, path = "new2.jpg")

        val imagesToUpsert = listOf(image1Updated, image2New)
        val returnedIds = noteImageDao.upserts(imagesToUpsert)

        assertEquals(2, returnedIds.size)
        assertTrue(returnedIds.containsAll(listOf(-1, testImageId2)))

        val retrievedImage1 = noteImageDao.get(testImageId1).first()
        assertNotNull(retrievedImage1)
        assertEquals("updated1.jpg", retrievedImage1.path)

        val retrievedImage2 = noteImageDao.get(testImageId2).first()
        assertNotNull(retrievedImage2)
        assertEquals("new2.jpg", retrievedImage2.path)

        assertEquals(2, noteImageDao.getByNoteId(testNoteId1).first().size)
    }

    @Test
    fun getByNoteId_returnsCorrectImages() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "p1.jpg"))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId2, path = "p2.jpg"))
        noteImageDao.upsert(NoteImageEntity(id = testImageId3, noteId = testNoteId1, path = "p3.jpg"))

        val imagesForNote1 = noteImageDao.getByNoteId(testNoteId1).first()
        assertEquals(2, imagesForNote1.size)
        assertTrue(imagesForNote1.all { it.noteId == testNoteId1 })
        assertTrue(imagesForNote1.any { it.id == testImageId1 && it.path == "p1.jpg" })
        assertTrue(imagesForNote1.any { it.id == testImageId3 && it.path == "p3.jpg" })

        val imagesForNote2 = noteImageDao.getByNoteId(testNoteId2).first()
        assertEquals(1, imagesForNote2.size)
        assertEquals(testNoteId2, imagesForNote2.first().noteId)
        assertEquals(testImageId2, imagesForNote2.first().id)
        assertEquals("p2.jpg", imagesForNote2.first().path)
    }

    @Test
    fun getImage_nonExistent() = runTest {
        val image = noteImageDao.get(9999L).first()
        assertNull(image)
    }

    @Test
    fun getAll_whenEmpty() = runTest {
        val allImages = noteImageDao.getAll().first()
        assertTrue(allImages.isEmpty(), "getAll should return an empty list for a fresh database")
    }

    @Test
    fun getAll_afterInserts() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "p1_all.jpg"))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId2, path = "p2_all.jpg"))
        val allImages = noteImageDao.getAll().first()
        assertEquals(2, allImages.size)
    }

    @Test
    fun deleteImage() = runTest {
        val image = NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "p_del.jpg")
        noteImageDao.upsert(image)
        assertNotNull(noteImageDao.get(testImageId1).first(), "Image should exist before delete")

        noteImageDao.delete(testImageId1)
        assertNull(noteImageDao.get(testImageId1).first(), "Image should be null after delete")
    }

    @Test
    fun deleteByNoteId_deletesAllImagesForNote() = runTest {
        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = "p1_n1_del.jpg"))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId1, path = "p2_n1_del.jpg"))
        noteImageDao.upsert(NoteImageEntity(id = testImageId3, noteId = testNoteId2, path = "p3_n2_keep.jpg"))

        noteImageDao.deleteByNoteId(testNoteId1)

        assertTrue(
            noteImageDao.getByNoteId(testNoteId1).first().isEmpty(),
            "Images for testNoteId1 should be deleted",
        )
        val imagesForNote2 = noteImageDao.getByNoteId(testNoteId2).first()
        assertEquals(1, imagesForNote2.size, "Should not delete images from other notes")
        assertEquals(testImageId3, imagesForNote2.firstOrNull()?.id)
    }

    @Test
    fun deleteNote_cascadesDeletesImages() = runTest {
        val imgPath1 = "cascade1.jpg"
        val imgPath2 = "cascade2.jpg"
        val imgPath3 = "no_cascade.jpg"

        noteImageDao.upsert(NoteImageEntity(id = testImageId1, noteId = testNoteId1, path = imgPath1))
        noteImageDao.upsert(NoteImageEntity(id = testImageId2, noteId = testNoteId1, path = imgPath2))
        noteImageDao.upsert(NoteImageEntity(id = testImageId3, noteId = testNoteId2, path = imgPath3))

        assertEquals(
            2,
            noteImageDao.getByNoteId(testNoteId1).first().size,
            "Pre-check: Note1 should have 2 images",
        )
        assertEquals(
            1,
            noteImageDao.getByNoteId(testNoteId2).first().size,
            "Pre-check: Note2 should have 1 image",
        )

        // Action: Delete the parent NoteEntity
        noteDao.delete(testNoteId1)

        // Assertions
        assertTrue(
            noteImageDao.getByNoteId(testNoteId1).first().isEmpty(),
            "Images for deleted note (testNoteId1) should be cascade deleted.",
        )
        assertNull(
            noteImageDao.get(testImageId1).first(),
            "Specific image 1 (id: $testImageId1) for deleted note should be gone.",
        )
        assertNull(
            noteImageDao.get(testImageId2).first(),
            "Specific image 2 (id: $testImageId2) for deleted note should be gone.",
        )

        val imagesForNote2 = noteImageDao.getByNoteId(testNoteId2).first()
        assertEquals(
            1,
            imagesForNote2.size,
            "Images for the other note (testNoteId2) should not be affected.",
        )
        assertEquals(testImageId3, imagesForNote2.first().id)
        assertEquals(imgPath3, imagesForNote2.first().path)
    }
}
